# Generated by Django 3.1.6 on 2021-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address_full', models.CharField(max_length=80)),
                ('address_city', models.CharField(max_length=45)),
                ('address_town', models.CharField(max_length=45)),
                ('fee1', models.IntegerField(null=True)),
                ('fee2', models.IntegerField(null=True)),
                ('bus', models.CharField(max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address_full', models.CharField(max_length=45)),
                ('courseA', models.CharField(max_length=500, null=True)),
                ('courseB', models.CharField(max_length=500, null=True)),
                ('courseC', models.CharField(max_length=500, null=True)),
                ('courseD', models.CharField(max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
