# Generated by Django 3.1.6 on 2021-02-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsite',
            name='phone_number',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
