# Generated by Django 3.1.5 on 2021-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_auto_20210204_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy_town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=45)),
                ('city_name', models.CharField(max_length=45)),
            ],
        ),
    ]
