# Generated by Django 3.1.5 on 2021-02-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsApp', '0002_testsite_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsite_review',
            old_name='academy_id',
            new_name='testsite_id',
        ),
    ]
